* Emacs 学习
  
** 初识Emacs
*** 核心概念
    Frame， 命令，快捷键
*** Emacs 的模式
    Emacs 是一种有模式的编辑器。Emacs中的模式分为主要模式（major mode）和次要模式（minor mode）两种    主要模式主要由文件类型决定，每个buffer打开文件时会根据文件类型决定其主要模式。次要模式可以组合到主要模式中。
    可以通过命令来指定模式： M-x mode_name 
    对于一个buffer来说，当前的主要模式只能有一种，当指定主要模式时，原来的主要模式会被替换，而当前的次要模式可以有多种
    如果输入的模式包含在当前的模式中，对于主要模式会清空所有的次要模式；对于次要模式，会关闭这个次要模式
    模式的变化可以在状态栏中看到
    
** 基本的编辑功能
*** 文件操作
文件操作的快捷键都集中在C-x 菜单中

快捷键             命令（M-x）             说明                  掌握情况
C-x C-f            find-file               打开文件或目录        已掌握
C-x C-c            save-buffers-kill-emacs 保存退出              已掌握
C-x C-z            iconify-or-deiconify-frame  挂起（最小化）    挂起之后，不知道怎么恢复
C-x C-r            find-file-read-only     以只读模式打开        打开的新文件，不知道如何关闭
C-x C-i            insert-file             插入文件              不知道该如何插入，主要是不知道该怎么复制
C-x C-s            save-buffer             保存                  已掌握
C-x s              save-some-buffers       保存所有未保存的缓冲区
C-x C-w            write-file              另存为文件            已掌握
C-x RET r                                  以指定编码读取文件
C-x RET f                                  以指定编码保存文件
revert-buffer                              恢复到原始状态        在不知道怎么操作
C-x d              dired                   进入到列表模式        可以进入到列表模式，但是进入后，不知道怎么退出
C-x C-d            list-directory          获取文件列表（简洁）  进入后，不知道怎么退出


*** 光标定位
                                                掌握情况
         向前      向后      向下    向上
翻页                         C-v     M-v         M-v 在mac 系统中，有粘贴的作用，不能向上翻页
字符     C-f       C-b       C-n     C-p
单词     M-f       M-b
句       M-a       M-e
行       C-a       C-e
段落     M-{       M-}
缓冲区   M-<       M->

其他：
M-g M-g  goto-line           跳转到某行         没有掌握，M 按键好像不生效，没办法跳转
M-x      goto-char           跳转到字符位置     自己不会
C-M-l    reposition-window   将当行卷至页面中部     不生效
C-l      recenter            刷新页面，将当前行卷至页面中部（使用数字参数指定行）
M-r M-x                      移动光标至页面中间的行（使用数字参数指定行）


*** 输入和删除
**** 输入：
     直接输入就可以了
**** 删除：
        向前         向后                  掌握情况
字符    C-d          DEL
单词    M-d          M-DEL
行      C-k （从光标处开始删除至行尾）     已掌握
整行    C-S-backspace                      没有掌握，不会
按表达式删除    C-M-k
区块    C-w
删除连续空格     M-x  delete-horizontal-space




aassdd法国国花fffff



    

*** 复制粘贴
复制之前要先选择： C-@开始区块选择，然后移动光光标，选中的区域会高亮   （不会操作）
剪切： 前面的“删除” 部分包括了一些剪切操作，对区块的剪切用C-w （区块的选择不会，导致这里的操作也不会）
复制：区块复制用M-ww  （mac 系统的command-w 会关闭控制台）
粘贴： C-y 粘贴 kill-ring 堆栈的最后一次的内容 （不会）
C-y 之后可以继续M-y ， 对 kill-ring 中的内容依此召回


*** 撤销重做
撤销： C-/ （每插入20个字符，视为一个undo 的单位）
重做： C-/ 之后，依此输入 C-g C-/ 就可以redo



    
本质上，快捷键只是一种发送命令的方法！*** 撤销重做
    
** 更有效的编辑
*** 核心概念
    窗口管理，缓冲区管理，  搜索和替换， 批量处理


*** 窗口管理

    快捷键      命令                       说明            掌握情况
    C-x 2       split-window-vertically    水平分割        可以完成水平分割，但是分割之后不知道如何恢复
    C-x 3       split-window-horizontally  垂直分割        可以完成垂直分割，并且可以通过Esc 来恢复
    c-x 1       delete-other-window        只保留当前窗口  可以完成操作。
    C-x 0       delete-window              关闭当前窗口    掌握
    C-x o       other-window               切换窗口        掌握
    C-M-v       scroll-other-window        滚动大下一个窗口 不知道怎么操作？？

    
*** 缓冲区管理
Emacs 中打开新的buffer，不会关闭原有的buffer，而是需要手工操作

    快捷键       命令             说明             掌握情况
    C-x C-b      list-buffers      查看缓冲区列表  掌握
    C-x b        switch-to-buffer  切换缓冲区       
    C-x k        kill-buffer       关闭缓冲区

    不知道怎么新建一个缓冲区

    
*** 搜索和替换
Emacs中的搜索包括增量搜索和一般搜索。增量搜索是每次在前一次搜索的结果基础上继续搜索。
在增量搜索时，如果上一次搜索之后进行了其他操作，则需要连续按两次快捷键才能召回关键字。
可以选中区块后在区块内进行搜索

增量搜索：
        快捷键       命令              说明           掌握情况
	C-s M-x      isearch-forward    向前增量搜索
	C-r M-x      isearch-backward   向后增量搜索

	其他搜索操作比较多，暂时先不整理。 前面的两个操作，搜索之后，不知道怎么在搜到的
	多个内容之间跳转。

	
*** 批量处理
批量处理的命令很多，这里只介绍两个
选中区域， M-x untabify  将TAB 字符转换为空格
选中区域， M-x indent-region 对齐文本块

** 简单的配置
*** 配置文件
   Emacs 的配置文件在 ~/.emacs. 可以通过重启emacs使配置生效，但是更快捷的方式是在打开 ./emacs 的时候执行命令 M-x eval-buffer，就可以使配置立即生效
(关于emacs 的配置生效的方式，自己没有掌握， 操作了但是没有生效
)

*** 安装插件
Emacs 的插件一般都是一个以el为后缀的文件。首先要指定一个插件目录，比如~/.emacs.d/lisps 然后再 ~/.emacs 中指定插件目录和要使用的插件：
(add-to-list 'load-path "~/.emacs.d/lisp/"')
(require 'pluginname')
   
*** 进阶
不要迷信自己，不要一开始就尝试自己定制Emacs， 一定要参考甚至抄袭大牛们的设置，比如 Steve Purcell（https://github.com/purcell/emacs.d）
学习他们的配置，不仅能让你直接学会“最佳实践” 更能加深你对Emacs 的理解

** 使用Emacs浏览网页
*** w3m
*** 如何在Emacs 中浏览网页

** org-mode 最好的文档编辑利器
*** 用大纲组织内容
emacs 最初和最基本的功能是通过大纲(outline)的方式来编辑文档，而且，无论是笔记管理，任务管理，还是项目计划的编写，都是对内容进行高效的组织(organization)为基础的
Org-mode 天然支持大纲视图，通过在文档中定义标题，可以方便的浏览每个小节，从而把握文档的总体内容。 Org是基于Outline模式的，它提供了更灵活的编辑结构文件的命令，比如折叠文档，针对大纲的编辑功能等，及其强大

**** 定义标题
注意：
1. * 要位于每行的行首
2. * 之后要有一个空格，然后再输入标题
3. 连续几个*就表示是第几级大纲，最多支持10级

  

注意：
1. *要位于每行的行首
2. *之后要有一个空格，然后再输入标题
3. 连续几个*就表示第几级大纲，最多支持10级

org-mode 真正的用处在于可以通过大纲操作文档，包括折叠，定位和编辑。而这些操作都是通过快捷键实现，非常有效率。尤其对大文档

**** 大纲相关的快捷键
***** 折叠大纲
      快捷键          命令            说明                                   掌握情况
      S-TAB           org-shifttab    循环切换整个文档的大纲状态(三种状态：折叠，打开下一级，打开全部)
      TAB             org-cycle       循环切换光标所在大纲的状态

      
***** 在大纲之间移动
      快捷键               命令            说明                       掌握情况
      C-c C-n/p                            上/下一标题                可以按一次C-c ，多次C-n/p 进行转移
      C-c C-f/b                            上/下一标题(仅限同级标题)
      C-c C-u                              跳到上一级标题
      C-c C-j                              切换到大纲浏览状态         只展示当前层级所属目录的大纲浏浏览状态，其他层级不会显示
      
      

***** 基于大纲编辑

      快捷键         命令    说明                          掌握情况
      M-RET                  插入一个同级标题              不会操作
      M-S-RET                插入一个同级的TODO标题        不会操作
      M-LEFT/RIGHT           当前标题提升/降级             不会操作
      M-S-LEFT/RIGHT         将子树升/降级                 不会操作
      M-S-UP/DOWN            将子树上/下移                 不会操作
      C-c *                  将本行设置为标题/正文         设置的级别为下一级别
      C-c C-w                将子树或区域移动到另一标题处(跨缓冲区)   不会操作
      C-x n s/w              只显示当前子树/返回
      C-c C-x b              在新缓冲区显示当前分支(类似 C-x n s)
      C-c /                  只列出包含搜索结果的大纲，并高亮，支持多种搜索方式
      C-c C-c                取消高亮
      
更多的快捷键可以通过C-c c-x C-h 查看 

     
**** 大纲的显示方式
默认的大纲显示没有缩进，显得有些乱。可以用M-x org-indent-mode 切换到另一种显示方式
(关于M-x 在mac 系统上面不知道对应什么操作 ？？)



*** 超链接和图文混排
**** 创建链接
对于符合链接规则的内容，org-mode会自动将其视为链接，包括文件，网页，邮箱，新闻组，BBDB数据库项，IRC会话和记录等


**** 内部链接
Org-mode支持内部链接
定义锚点  #<<my-auchor>> [[my-anchor][link]
脚注可以看作是一种特殊的内部链接，但是要求具 fn: 前缀：
    添加脚注链接  [[fn:footprint1]  [脚注]]   (实际编写的时候，不能有空格)
    定义脚注： [fn:footprint1]
    
    
    
     
*** 轻量级标记语言

*** 标签

*** 导出和发布
    
** org-mod 最强的任务管理利器

** 帮助系统
   C-h 打开Emacs的帮助Frame [O

** 常用的快捷键
*** 已经掌握的快捷键
    C-h 查看emacs 的帮助系统
    C-h i 查看Emacs的学习指南
    

*** 想要掌握的快捷键
    Emacs中鼠标如何在文档中快速移动
    
本质上，快捷键只是一种发送命令的方法！本质上，快捷键只是一种发送命令的方法！本质上，快捷键只是一种发送命令的方法！本质上，快捷键只是一种发送命令的方法！本质上，快捷键只是一种发送命令的方法！本质上，快捷键只是一种发送命令的方法！本质上，快捷键只是一种发送命令的方法！本质上，快捷键只是一种发送命令的方法！本质上，快捷键只是一种发送命令的方法！    
    
** 学会的操作
通过C-h 查看emacs的帮助文档， 在mac系统中有中文文档
Emacs 文件的保存 C-x C-c

** 不会的操作
   Emacs中不同模式之间的切换， M-x mode_name 自己不会用？
   Emacs中关于C-h 打开的帮助Frame ？
   Emacs中通过C-x C-z 将Emacs 挂起之后，不知道该如何恢复？
   Emacs中通过C-x C-c 保存文件内容后，会退出，有没有什么快捷键可以保存但是不退出
   Emacs中显示行号
   
